name: Pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - name: checkout code
              uses: actions/checkout@v4

            # Set up NodeJS
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 14

            # Install NodeJS Dependencies
            - name: Install NodeJS dependencies
              run: npm install
            # SonarQube Analysis
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v4
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            # Docker Image Build
            - name: Build Docker Image
              run: |
                docker build -t actions-app:${{github.sha}} .
                docker tag actions-app:${{github.sha}} ${{secrets.ECR_REPOSITORY_URI}}/action-cicd:latest
                docker tag actions-app:${{github.sha}} ${{secrets.DOCKERHUB_USERNAME}}/action-cicd:latest

            # Trivy Scan
            - name: Trviy Scan
              run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image actions-app:${{github.sha}}


            # Set up AWS Credentials
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              #uses: jwalton/gh-ecr-login@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{secrets.AWS_REGION}}

            # Log in to Amazon ECR
            - name: Log into Amazon ECR
              run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_REPOSITORY_URI}}

            # Push IMage to Amazon ECR
            - name: Push Image to amazon ECR
              run: docker push ${{secrets.ECR_REPOSITORY_URI}}/action-cicd:latest
              env:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{secrets.AWS_REGION}}

            # Log in to Dockerhub
            - name: Log in to Dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            # Push Image to Dockerhub
            - name: Push Image Into Dockerhub
              run:
                docker push ${{secrets.DOCKERHUB_USERNAME}}/action-cicd:latest

