name: Pipeline
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - name: checkout code
              uses: actions/checkout@v4

            # Set up NodeJS
            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 14

            # Install NodeJS Dependencies
            - name: Install NodeJS dependencies
              run: npm install
            # SonarQube Analysis
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v4
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            # Docker Image Build
            - name: Build Docker Image
              run: docker build -t $GITHUB_SHA .

            # Trivy Scan
            - name: Trviy Scan
              run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image $GITHUB_SHA


            # Set up AWS Credentials
            - name: Configure AWS Credentials
              #uses: aws-actions/configure-aws-credentials@v2
              uses: jwalton/gh-ecr-login@v3
              with:
                access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                region: ${{secrets.AWS_REGION}}

            # Log in to Amazon ECR
            - name: Log into Amazon ECR
              run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_REPOSITORY_URI}}




